apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: tyk
spec:
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  type: ClusterIP
