apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: graviti
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        kubernetes.io/hostname: pool-pno4qqu2l-lns6b
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - pool-pno4qqu2l-lns6b
      containers:
      - name: mongos
        image: mongo
        ports:
          - containerPort: 27017
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.1"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "root123!"
        volumeMounts:
          - name: mongops
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongops
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: do-block-storage-xfs
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: graviti
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo